import { Outfit } from "next/font/google";
import "./globals.css";
import Providers from "./providers";


const outfit= Outfit({subsets: ["latin"], weight:["400","500","600","700"]});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
